# Audiobookshelf is an open-source self-hosted media server for your audiobooks and podcasts.
# Reference: https://www.audiobookshelf.org/docs

services:
  audiobookshelf:
    restart: unless-stopped
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 12250:80
    volumes:
      - ./Audiobooks:/audiobooks
      - ./Books:/books
      - ./Podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
    environment:
      - TZ=India/Kolkata
